name: "parse and deploy"
on:
  #schedule:
  #  - cron:  '05 4 * * *'
  push:


jobs:
  build:
    runs-on: ubuntu-latest
    name: parse options and create search
    steps:

      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: update gitignore
        run: echo result > .gitignore

      - run: |
          nix --version

          #nix run nixpkgs\#nixVersions.nix_2_24 -- __dump-language | nix run nixpkgs#jq -- '[ to_entries[] | .value += {"title":.key} | .value] | { "options": .}' > data/builtins-2.24.json
          #nix run nixpkgs\#nixVersions.nix_2_18 -- __dump-language | nix run nixpkgs#jq -- '.builtins | [ to_entries[] | .value += {"title":.key} | .value] | { "options": .}' > data/builtins-2.18.json

      - name: Build Hugo
        run: nix run nixpkgs#hugo -- --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: pages-${{ github.ref_name }}
          publish_dir: ./public

