name: "parse and deploy"
on:
  schedule:
    - cron:  '05 4 * * *'
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: parse options and create search
    steps:

      - uses: cachix/install-nix-action@v22
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
        #- run: nix build
        #- run: nix flake check

      - run: |
          rm -v data/builtins1.json data/builtins2.json
          nix --version
          nix __dump-language > data/builtins1.json
          nix develop --command nix __dump-language > data/builtins1.json
          cat data/builtins1.json | nix develop --command jq '.builtins | [ to_entries[] | .value += {"title":.key} | .value]' > data/builtins2.json

          ls -al data/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
